### PR TITLE
Feature coderefactor

### PR DESCRIPTION
**Pull request by olsenme**
Hey guys, 
So I did a bit of cleaning up. Compiles and runs on my local machine. I did do some stuff that Joseph had done in his commits on his branch as I understand, but check it out. Let me know if you have questions.

### CODE REVIEW

**Comment by zainkai** [comment]
The changed numbers and letters for boards look fine. Why is there a bunch of unnecessary additions and deletions of the same code? Please redo this with proper git procedure.

**Comment by olsenme** [comment]
Thank you. I used proper got procedure and unfortunately since Joseph did not put in a pull request to merge his code with master, I am unable to pull his changes down to my branch. I simply did what I said I would in my issue.

**Comment by zainkai** [comment]
Okay, merge it anyways. But why is there over 1000+ line changes with only roughly 30 lines actually changed? That makes code reviews tedious, and on the off chance we need to rollback it's easier to see what has been changed.

**Comment by Makumasa** [comment]
Please redo this pull request since Joseph's changes are now merged to master. I can't do a proper code review when the deltas are this large because GIT in under the false impression that entire files are being remade from scratch which should not be the case. It also makes it difficult/impossible to tell what is actually being changed.

**Pull request closed without merging**
